import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useState } from "react";

interface ImageGridProps {
  urls: Array<string>;
}

function getImageUrls(n: number, min: number, max: number): string[] {
  min = Math.ceil(min);
  max = Math.floor(max);
  const res: string[] = new Array<string>(n);
  for (let i = 0; i < n; i++) {
    const randIdx = Math.floor(Math.random() * (max - min) + min);
    res[i] = `/emb/seed0${randIdx}.png`;
  }
  return res;
}
function ImageGrid({ urls }: ImageGridProps) {
  return (
    <div
      className="mt-2 mx-auto grid h-4/5 w-11/12 grid-cols-2 content-evenly 
    items-center justify-evenly justify-items-center gap-y-2 gap-x-2 sm:grid-cols-3"
    >
      {urls.map((url, idx) => (
        <div
          key={idx}
          className="inline-flex overflow-hidden rounded-xl bg-gray-300 ring-2 ring-blue-300 focus-within:ring-2 
            focus-within:ring-indigo-500 focus-within:ring-offset-2 focus-within:ring-offset-gray-100"
        >
          <Image
            height={280}
            width={280}
            alt="Image of Ukrainian embroidery generated by AI"
            src={url}
            className="rounded-xl object-cover"
          />
        </div>
      ))}
    </div>
  );
}
const Home: NextPage = () => {
  const [imageUrls, setImageUrls] = useState(getImageUrls(6, 600, 651));
  console.log(imageUrls);
  return (
    <div className="h-screen flex-col bg-[#fffef9]">
      <Head>
        <title>Generate Ukrainian Embroidery</title>
        <meta
          name="description"
          content="Ukrainian Embroidery generated by AI"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-4 flex justify-start border-black">
        <Link href="https://uaembroidery.com">
          <p className="mx-4 mt-2 text-start font-mono text-xl font-bold text-slate-600">
            Home
          </p>
        </Link>
      </div>
      <ImageGrid urls={imageUrls} />
      <div className="flex justify-center">
        <button
          className="active:text-yellowish mt-4 justify-between rounded-md bg-slate-600 px-4 py-4 text-center font-semibold text-[#fffef9] 
        hover:bg-slate-900 focus:outline-none focus-visible:outline-2
        focus-visible:outline-offset-2 focus-visible:outline-slate-700"
          onClick={() => setImageUrls(getImageUrls(6, 600, 651))}
        >
          Generate
        </button>
      </div>
    </div>
  );
};

export default Home;
